<?php
function landing_pages_preprocess_page(&$vars)  {
    $node = node_load(2811);
    $vars['apply_online_form'] = drupal_get_form('webform_client_form_2811',$node,array());
}

function landing_pages_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'webform_client_form_2811') {
    if ($node = menu_get_object()) {
      $form['submitted']['part']['#value'] = $node->field_webform_part_value['0']['value'];
    }
  }
} 

/**
 * Implementation of hook_views_api().
 */
function landing_pages_views_api() { // your module name into hook_views_api
  return array(
    'api' => 2,
    // might not need the line below, but in any case, the last arg is the name of your module
    'path' => drupal_get_path('module', 'landing_pages'),
  );
}

